# Configuration pour le service BACKEND uniquement
# Le frontend aura son propre service Railway

[phases.setup]
nixPkgs = ["python312"]

[phases.install]
# Railway détecte automatiquement uv.lock et utilise: uv sync --no-dev --frozen
# Pas besoin de commandes manuelles

[start]
cmd = "uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"