# Render Blueprint Configuration - PgBouncer Integration
# Context7 Documentation Compliant - Official Render PostgreSQL Connection Pooling Pattern

databases:
  - name: arbitragevault-postgres
    databaseName: arbitragevault
    user: arbitragevault_user

services:
  # PgBouncer Connection Pooling Service - Context7 Official Pattern
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: standard
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arbitragevault-postgres
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50

  # Backend FastAPI Service - Main Application
  - type: web
    name: arbitragevault-backend-v2
    runtime: python
    buildCommand: "uv sync --no-dev"
    startCommand: "uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: pgbouncer
          property: connectionString
      - key: KEEPA_API_KEY
        sync: false
      - key: FASTAPI_ENV
        value: production
      - key: AUTOSOURCING_ENGINE_URL  
        sync: false