services:
  # Frontend - Static Site (React + Vite)
  - type: web
    name: arbitragevault-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: arbitragevault-backend
          property: host
        
  # Backend - Python FastAPI
  - type: web
    name: arbitragevault-backend
    runtime: python3
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arbitragevault-db
          property: connectionString
      - key: KEEPA_API_KEY
        sync: false # Secret variable to be set in Render dashboard

  # Database - PostgreSQL
  - type: database
    name: arbitragevault-db
    databaseName: arbitragevault
    plan: free