version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: arbitragevault_postgres_dev
    environment:
      POSTGRES_USER: memex
      POSTGRES_PASSWORD: memex
      POSTGRES_DB: memex
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memex -d memex"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - arbitragevault_dev

  # Redis for future rate limiting (Phase 2)
  # redis:
  #   image: redis:7-alpine
  #   container_name: arbitragevault_redis_dev
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   restart: unless-stopped
  #   networks:
  #     - arbitragevault_dev

volumes:
  postgres_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  arbitragevault_dev:
    driver: bridge